### ISSUE TITLE
[Front-end] scrollbar do not has darkcolor in Darkmode Theme

### ISSUE THREAD

**Issue by atom-tr** [dathoangnd/truedevtools.com#8]
Your Operating System: Window 11  
Your Web Browser: Microsoft Edge

**This must be done to see the problem**

1.  Go to truedevtools.com

![](https://github.com/dathoangnd/truedevtools.com/assets/65351520/0a3e2583-9133-472a-be9c-e0b49cc02892)

## Solution

Add some css for darkmode:

```css
html[data-theme="dark"] {
    .ant-menu-root, main > .overflow-y-auto {
	
		&:hover::-webkit-scrollbar-corner {
			width: 10px;
		}
		/* Let's get this party started */
		&::-webkit-scrollbar {
			width: 10px;
			&:hover {
				width: 15px;
			}
		}
		/* Track */
		&::-webkit-scrollbar-track {
			-webkit-box-shadow: inset 0 0 6px rgba(0,0,0,0); 
			-webkit-border-radius: 5px;
			border-radius: 5px;
		}
		/* Handle */
		&::-webkit-scrollbar-thumb {
			-webkit-border-radius: 6px;
			border-radius: 6px;
			background: #424242; 
        	border: solid 1px #141414;
			/* -webkit-box-shadow: inset 0 0 6px rgba(0,0,0,0.5);  */
		}
	}
}
```

It will look like

![](https://github.com/dathoangnd/truedevtools.com/assets/65351520/ee494d9e-6974-48f1-9b7c-bd968e7782b7)
